name: Deploy to ECS

on:
  push:
    branches:
      - main  # This workflow triggers on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build, tag, and push Docker image
        run: |
          docker build -t cost-estimator .
          docker tag cost-estimator:latest ${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Update ECS service with the new image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLUSTER: ${{ secrets.ECS_CLUSTER }}
          SERVICE: ${{ secrets.ECS_SERVICE }}
        run: |
          aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment
